@startmindmap diameter-of-binary-tree

skinparam backgroundColor #EEEBDC
skinparam handwritten true
top to bottom direction

* 1
** 2
*** 4
**** 8
**** 9
*** 5
** 3
*** 6
**** 10
***** 14
***** 15
****** 20
****** 21
******* 24
******* 25
**** 11
*** 7
**** 12
***** 16
***** 17
**** 13
***** 18
****** 22
****** 23
******* 26
******* 27
***** 19
@endmindmap